spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.56.181.180:3306/desktoptest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 3000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/view/,classpath:/,classpath:/static

  redis:
    host: 127.0.0.1
    port: 6379
    # 根据自己设置的密码决定
    password:
    # 操作0号数据库，默认有16个数据库
    database: 0


feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.cestc.os.desktop.model

cas:
  client:
    clientId: client1
    clientSecret: 12345678

  serverUrl: 'http://172.18.1.67/cas-server-webapp-3.5.2'
  appUrl: 'http://172.18.1.67/cas-server-webapp-3.5.2/login'
  server-login-url: 'http://172.18.1.67/cas-server-webapp-3.5.2/login'
  casLogoutUrl: redirect:http://172.18.1.67/cas-server-webapp-3.5.2/logout?service=http://172.18.1.67/cas-server-webapp-3.5.2/login




#logging:
#  config: classpath:logback-spring.xml

# Sa-Token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  isReadCookie: false

# SSO配置
sso:
  loginUrl: http://10.56.183.138:8889/login
  logoutUrl: http://10.56.183.138:8889/logout
  ifLoginUrl: http://localhost:8889/ifLogin
  getSessionUrl: http://10.56.183.138:8889/session
  getPermissionsUrl: http://10.56.183.138:8889/permissions
  getUserUrl: http://10.56.183.138:8889/user?uid={uid}
